services:
  - type: web
    name: tg-ai-bot
    runtime: python
    repo: https://github.com/modixname/bot67
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:server
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER_URL
        value: https://tg-ai-bot-5lfr.onrender.com
      - key: WEBHOOK_URL
        value: https://tg-ai-bot-5lfr.onrender.com
